<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Farewell.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Farewell.Abstractions\Farewell.Abstractions.csproj" />
    </ItemGroup>

</Project>
