<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Farewell.Compatibility.MS.DependencyInjection\Farewell.Compatibility.MS.DependencyInjection.csproj" />
      <ProjectReference Include="..\Farewell.Configuration\Farewell.Configuration.csproj" />
      <ProjectReference Include="..\Farewell.Debug.ASP.Application\Farewell.Debug.ASP.Application.csproj" />
      <ProjectReference Include="..\Farewell.Infrastructure.EntityFramework\Farewell.Infrastructure.EntityFramework.csproj" />
      <ProjectReference Include="..\Farewell.Localization\Farewell.Localization.csproj" />
      <ProjectReference Include="..\Farewell.Validation\Farewell.Validation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    </ItemGroup>

</Project>
