<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Farewell.Abstractions</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>starplays</Authors>
        <Description>Farewell.Abstractions</Description>
        <RepositoryUrl>https://github.com/starplaysyt/Farewell</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

</Project>
