<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>starplaysyt</Authors>
        <Description>Farewell.Compatibility.MS.DependencyInjection</Description>
        <RepositoryUrl>https://github.com/starplaysyt/Farewell</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Farewell.Abstractions\Farewell.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    </ItemGroup>

</Project>
